version: "3"
services:
  api:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: node-api
    volumes:
      - ./backend:/app
      - /backend/node_modules
    environment:
      - SECRET=mysecret
    networks: [webappnetwork]

  web-client:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: react-ui
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /frontend/node_modules
    links:
      - api
    networks: [webappnetwork]

  web-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: web-server
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - api
      - web-client
    ports:
      - "3000:80"
    networks: [webappnetwork]

networks:
  webappnetwork:
    driver: bridge
